"use client";

import React, { createContext, useContext, useState } from "react";

type VacancyLanguage = "en" | "ne";

interface VacancyLanguageContextType {
  language: VacancyLanguage;
  setLanguage: (lang: VacancyLanguage) => void;
  t: (key: string) => string;
}

const VacancyLanguageContext = createContext<VacancyLanguageContextType | undefined>(undefined);

export const vacancyTranslations: Record<VacancyLanguage, Record<string, string>> = {
  en: {
    "vacancy.candidates": "Candidate Dashboard",
    "vacancy.portal": "Vacancy portal",
    "vacancy.title": "Open Positions",
    "vacancy.description": "Browse current openings and find the role that matches your skills and experience.",
    "vacancy.careers": "Careers",
    "vacancy.openCompetition": "Open Competition",
    "vacancy.internalCompetition": "Internal Competition",
    "vacancy.advertisementNo": "Advertisement No.",
    "vacancy.publishedDate": "Published Date",
    "vacancy.deadline": "Deadline",
    "vacancy.doubleFeeDeadline": "Double Fee Deadline",
    "vacancy.type": "Type",
    "vacancy.openInclusive": "Open / Inclusive",
    "vacancy.noOfPosts": "No. of Posts",
    "vacancy.action": "Action",
    "vacancy.filter": "Filter...",
    "vacancy.noVacancies": "No vacancies found.",
    "vacancy.loginToApply": "Login to Apply",
    "vacancy.viewDetails": "View Details",
    "vacancy.backToHome": "Back to Home",
    "vacancy.applyNow": "Apply Now",
    "vacancy.detailsTitle": "Vacancy Details",
    "vacancy.overview": "Overview",
    "vacancy.requirements": "Requirements",
    "vacancy.loadingDetails": "Loading vacancy details...",
    "vacancy.detailsUnavailable": "Unable to load vacancy details",
    "vacancy.publishedLabel": "Published",
    "vacancy.salaryLabel": "Salary",
    "vacancy.ageRestrictionLabel": "Age Restriction",
    "vacancy.experienceLabel": "Experience Required",
    "vacancy.applicationFeeLabel": "Application Fee",
    "vacancy.close": "Close",
    "vacancy.backToVacancies": "Back to Vacancies",
    "vacancy.aboutRole": "About this role",
    "vacancy.applyPosition": "Apply for this position",
    "vacancy.applicationFormTitle": "Online Application Form",
    "vacancy.personalDetail": "Personal Detail",
    "vacancy.gender": "Gender",
    "vacancy.dateOfBirth": "Date of Birth",
    "vacancy.dob": "Date of Birth",
    "vacancy.nameEnglish": "Name (In English)",
    "vacancy.nameNepali": "Name (In Nepali)",
    "vacancy.firstName": "First Name",
    "vacancy.middleName": "Middle Name",
    "vacancy.lastName": "Last Name",
    "vacancy.firstNamePreeti": "First Name (Preeti Unicode)",
    "vacancy.middleNamePreeti": "Middle Name (Preeti Unicode)",
    "vacancy.lastNamePreeti": "Last Name (Preeti Unicode)",
    "vacancy.required": "Required",
    "vacancy.optional": "optional",
    "vacancy.step": "Step",
    "vacancy.personalIntro": "Enter your identity and citizenship details carefully. Fields marked * are required.",
    "vacancy.dobTitle": "Date of Birth",
    "vacancy.inBS": "In BS",
    "vacancy.inAD": "In AD",
    "vacancy.citizenshipTitle": "Citizenship",
    "vacancy.issuedDateBS": "Issued Date (BS)",
    "vacancy.familyDetails": "Family Details",
    "vacancy.familyDetailsHint": "Enter family names as they appear on official records. First and last names are required.",
    "vacancy.middleOptional": "Middle name is optional.",
    "vacancy.spouseTitle": "Husband / Wife Name",
    "vacancy.spouseHintTitle": "Conditional spouse details",
    "vacancy.spouseHint": "When married, the husband / wife name fields appear automatically.",
    "vacancy.selectOption": "Select...",
    "vacancy.single": "Single",
    "vacancy.married": "Married",
    "vacancy.divorced": "Divorced",
    "vacancy.male": "Male",
    "vacancy.female": "Female",
    "vacancy.other": "Other",
    "vacancy.priorityProvince": "I am from a priority province (1, 3, 4, 5)",
    "vacancy.fieldComplete": "Looks good",
    "vacancy.footerDescription": "CYC Nepal Laghubitta Bittiya Sanstha Ltd. — committed to inclusive financial access and building careers across Nepal.",
    "vacancy.footerRights": "All rights reserved.",
    "vacancy.contactIntro": "Provide your permanent and temporary addresses in English and Nepali, plus your contact information.",
    "vacancy.referencesTitle": "References",
    "vacancy.referencesHint": "Optional. Add people who can vouch for your application.",
    "vacancy.reference": "Reference",
    "vacancy.referenceName": "Name",
    "vacancy.referencePhone": "Phone",
    "vacancy.position": "Position",
    "vacancy.educationIntro": "Add your academic qualifications. Each entry can be edited or removed.",
    "vacancy.experienceIntro": "Add your work history. Each entry can be edited or removed.",
    "vacancy.documentsIntro": "Upload the required documents. Accepted file types and size limits are shown under each item.",
    "vacancy.documents": "Documents",
    "vacancy.facultyNepali": "Faculty (Preeti Unicode)",
    "vacancy.englishLabel": "English",
    "vacancy.nepaliLabel": "Nepali",
    "vacancy.noEducationYet": "No education added yet.",
    "vacancy.noExperienceYet": "No experience added yet.",
    "vacancy.addAnother": "Add another",
    "vacancy.edit": "Edit",
    "vacancy.save": "Save",
    "vacancy.done": "Done",
    "vacancy.cancel": "Cancel",
    "vacancy.actions": "Actions",
    "vacancy.optionalDoc": "Optional",
    "vacancy.overviewIntro": "Review every detail before you submit. Use the step tabs above to go back and edit.",
    "vacancy.profile": "Profile",
    "vacancy.changePassword": "Change Password",
    "vacancy.logoff": "Log off",
    // Contact fields
    "vacancy.contactDetail": "Contact Detail",
    "vacancy.permanentAddress": "Permanent Address",
    "vacancy.temporaryAddress": "Temporary Address",
    "vacancy.state": "State",
    "vacancy.district": "District",
    "vacancy.localLevelType": "Local Level Type",
    "vacancy.municipality": "Municipality/Rural Municipality",
    "vacancy.ward": "Ward No",
    "vacancy.tole": "Tole",
    "vacancy.street": "Street Name",
    "vacancy.streetName": "Street Name",
    "vacancy.wardNo": "Ward No",
    "vacancy.houseNo": "House No",
    "vacancy.phone": "Phone",
    "vacancy.email": "Email",
    "vacancy.sameAsPermanent": "Same as Permanent Address",
    "vacancy.permanentAddressNepali": "Permanent Address (Nepali)",
    "vacancy.temporaryAddressNepali": "Temporary Address (Nepali)",
    "vacancy.contactInformation": "Contact Information",
    "vacancy.mobile": "Mobile",
    "vacancy.maritalStatus": "Marital Status",
    "vacancy.citizenshipNumber": "Citizenship Number",
    "vacancy.citizenshipDistrict": "Citizenship Issue District",
    "vacancy.citizenshipDate": "Citizenship Issue Date",
    "vacancy.fatherName": "Father Name",
    "vacancy.motherName": "Mother Name",
    "vacancy.spouseName": "Spouse Name",
    "vacancy.grandfatherName": "Grandfather Name",
    "vacancy.religion": "Religion",
    "vacancy.disability": "Disability",
    "vacancy.documentDetail": "Document Detail",
    "vacancy.documentType": "Document Type",
    "vacancy.documentTitle": "Document Title",
    "vacancy.download": "Download",
    "vacancy.preview": "Preview",
    // Education fields
    "vacancy.education": "Education",
    "vacancy.addEducation": "+ Add Education Detail",
    "vacancy.university": "University/Board Name",
    "vacancy.institution": "Institution",
    "vacancy.degree": "Degree",
    "vacancy.faculty": "Faculty",
    "vacancy.marks": "Marks",
    "vacancy.educationNepali": "Education (In Nepali)",
    "vacancy.universityNepali": "University/Board Name (Preeti Unicode)",
    "vacancy.institutionNepali": "Institution (Preeti Unicode)",
    "vacancy.degreeNepali": "Degree (Preeti Unicode)",
    "vacancy.delete": "Delete",
    // Experience fields
    "vacancy.experience": "Experience",
    "vacancy.addExperience": "+ Add Experience",
    "vacancy.organization": "Organization Name",
    "vacancy.department": "Department",
    "vacancy.serviceFrom": "Service From",
    "vacancy.serviceTo": "Service To",
    "vacancy.organizationNepali": "Organization Name (Preeti Unicode)",
    "vacancy.departmentNepali": "Department (Preeti Unicode)",
    "vacancy.positionNepali": "Position (Preeti Unicode)",
    // Documents & additional notes
    "vacancy.requiredDocumentsTitle": "Required Documents",
    "vacancy.doc.handwrittenApplication": "Handwritten application",
    "vacancy.doc.cv": "Bio-data / CV",
    "vacancy.doc.citizenship": "Citizenship copy",
    "vacancy.doc.educationalCertificates": "Educational certificates",
    "vacancy.doc.experienceCertificates": "Experience certificates",
    "vacancy.doc.photograph": "Passport-size photograph",
    "vacancy.doc.trainingCertificates": "Training certificates (if any)",
    "vacancy.allDocumentsPdf": "Upload each document in the format and size shown below it.",
    "vacancy.workLocation": "Selected candidates may be assigned to any branch, province, cluster, or department according to organizational needs.",
    "vacancy.additionalPreferencesTitle": "Additional Preferences",
    "vacancy.pref.motorcycleLicense": "Possess a motorcycle driving license",
    "vacancy.pref.computerKnowledge": "Have computer knowledge",
    "vacancy.pref.microfinanceExperience": "Have experience in microfinance institutions",
    "vacancy.mandatoryEconomicsQuestion": "Did you study Economics as a compulsory subject?",
    "vacancy.mandatoryEconomicsNote": "Candidates from Management and Education (Arts & Education) streams must have studied Economics as a compulsory subject.",
    // --- Candidate shell / navigation ---
    "vacancy.candidateSection": "Candidate Section",
    "vacancy.onlineApplicationSystem": "Online Application System",
    "vacancy.home": "Home",
    "vacancy.previous": "Back",
    "vacancy.next": "Next",
    "vacancy.applyHeading": "Input the following information to apply for the job",
    "vacancy.applicationType": "Application Type",
    "vacancy.confirmApply": "I have carefully read all instructions, completed all required documents, and applied for the job.",
    "vacancy.payNow": "Save your information and pay now",
    // --- Save / storage ---
    "vacancy.saveDraft": "Save Form",
    "vacancy.draftSaved": "Saved",
    "vacancy.saving": "Saving…",
    "vacancy.saveDraftHint": "You can save your unfinished form and return to it later.",
    "vacancy.attachmentStorage": "Attachment storage",
    "vacancy.maxLabel": "Max",
    // --- Family (Nepali) + hints ---
    "vacancy.familyDetailsNepali": "Family Details (Nepali)",
    "vacancy.fatherNameNepali": "Father's Name (Nepali)",
    "vacancy.motherNameNepali": "Mother's Name (Nepali)",
    "vacancy.grandfatherNameNepali": "Grandfather's Name (Nepali)",
    "vacancy.spouseTitleNepali": "Husband / Wife Name (Nepali)",
    "vacancy.devanagariHint": "Type in Nepali (Devanagari), e.g. राम बहादुर",
    "vacancy.englishHint": "Type in English (A–Z)",
    // --- Documents (labels + notes) ---
    "vacancy.doc.citizenshipFront": "Citizenship (front)",
    "vacancy.doc.citizenshipBack": "Citizenship (back)",
    "vacancy.doc.experienceLetter": "Experience letter",
    "vacancy.doc.referenceLetter": "Reference letter",
    "vacancy.requiredDocsIntro": "Upload clear scans. The accepted file type and size limit are shown under each item.",
    "vacancy.replaceFile": "Replace",
    "vacancy.chooseFile": "Choose file",
    "vacancy.docRequired": "This document is required.",
    // --- Education detail form ---
    "vacancy.educationDetailTitle": "Educational Qualification Detail",
    "vacancy.boardUniversity": "Board / University Name",
    "vacancy.otherBoardUniversity": "Other University / Board Name",
    "vacancy.academicDegree": "Academic Degree",
    "vacancy.facultyGroup": "Faculty / Group",
    "vacancy.otherFaculty": "Other Academic Faculty",
    "vacancy.mainSubject": "Main Subject",
    "vacancy.gradeType": "Grade / Division",
    "vacancy.gradeName": "Grade / Division Name",
    "vacancy.gpa": "GPA / Percentage",
    "vacancy.eduCertificate": "Educational Certificate",
    "vacancy.characterCertificate": "Character Certificate",
    "vacancy.equivalenceCertificate": "Equivalence Certificate",
    "vacancy.eduUploadNote": "Upload only .jpg, .jpeg, .png, or .pdf",
    "vacancy.othersOption": "Others",
    "vacancy.gradeOption": "Grade",
    "vacancy.divisionOption": "Division",
    "vacancy.percentageOption": "Percentage",
  },
  ne: {
    "vacancy.candidates": "उम्मेदवार ड्यासबोर्ड",
    "vacancy.portal": "रिक्ति पोर्टल",
    "vacancy.title": "खुला पदहरू",
    "vacancy.description": "हालका रिक्तिहरू हेर्नुहोस् र आफ्नो सीप तथा अनुभवसँग मेल खाने पद फेला पार्नुहोस्।",
    "vacancy.careers": "क्यारियर",
    "vacancy.openCompetition": "खुला प्रतिस्पर्धा",
    "vacancy.internalCompetition": "आन्तरिक प्रतिस्पर्धा",
    "vacancy.advertisementNo": "विज्ञापन नम्बर",
    "vacancy.publishedDate": "प्रकाशित मिति",
    "vacancy.deadline": "अन्तिम मिति",
    "vacancy.doubleFeeDeadline": "दोब्बर शुल्क अन्तिम मिति",
    "vacancy.type": "प्रकार",
    "vacancy.openInclusive": "खुला / समावेशी",
    "vacancy.noOfPosts": "पद संख्या",
    "vacancy.action": "कार्य",
    "vacancy.filter": "फिल्टर गर्नुहोस्...",
    "vacancy.noVacancies": "कुनै रिक्ति फेला परेन।",
    "vacancy.loginToApply": "आवेदन दिन लगइन गर्नुहोस्",
    "vacancy.viewDetails": "विवरण हेर्नुहोस्",
    "vacancy.backToHome": "गृहपृष्ठमा फर्किनुहोस्",
    "vacancy.applyNow": "अहिले आवेदन दिनुहोस्",
    "vacancy.detailsTitle": "रिक्ति विवरण",
    "vacancy.overview": "सारांश",
    "vacancy.requirements": "आवश्यकताहरू",
    "vacancy.loadingDetails": "रिक्ति विवरण लोड हुँदैछ...",
    "vacancy.detailsUnavailable": "रिक्ति विवरण लोड गर्न सकिएन",
    "vacancy.publishedLabel": "प्रकाशित",
    "vacancy.salaryLabel": "तलब",
    "vacancy.ageRestrictionLabel": "उमेर सीमा",
    "vacancy.experienceLabel": "आवश्यक अनुभव",
    "vacancy.applicationFeeLabel": "आवेदन शुल्क",
    "vacancy.close": "बन्द गर्नुहोस्",
    "vacancy.backToVacancies": "रिक्ति सूचीमा फर्किनुहोस्",
    "vacancy.aboutRole": "यो पदको बारेमा",
    "vacancy.applyPosition": "यो पदका लागि आवेदन दिनुहोस्",
    "vacancy.applicationFormTitle": "अनलाइन आवेदन फाराम",
    "vacancy.personalDetail": "व्यक्तिगत विवरण",
    "vacancy.gender": "लिङ्ग",
    "vacancy.dateOfBirth": "जन्म मिति",
    "vacancy.dob": "जन्म मिति",
    "vacancy.nameEnglish": "नाम (अंग्रेजीमा)",
    "vacancy.nameNepali": "नाम (नेपालीमा)",
    "vacancy.firstName": "पहिलो नाम",
    "vacancy.middleName": "बीचको नाम",
    "vacancy.lastName": "अन्तिम नाम",
    "vacancy.firstNamePreeti": "पहिलो नाम (प्रीति युनिकोड)",
    "vacancy.middleNamePreeti": "बीचको नाम (प्रीति युनिकोड)",
    "vacancy.lastNamePreeti": "अन्तिम नाम (प्रीति युनिकोड)",
    "vacancy.required": "अनिवार्य",
    "vacancy.optional": "वैकल्पिक",
    "vacancy.step": "चरण",
    "vacancy.personalIntro": "कृपया आफ्नो परिचय र नागरिकता विवरण ध्यानपूर्वक भर्नुहोस्। * लगाइएका विवरण अनिवार्य छन्।",
    "vacancy.dobTitle": "जन्म मिति",
    "vacancy.inBS": "बि.सं.मा",
    "vacancy.inAD": "ई.सं.मा",
    "vacancy.citizenshipTitle": "नागरिकता",
    "vacancy.issuedDateBS": "जारी मिति (बि.सं.)",
    "vacancy.familyDetails": "परिवार विवरण",
    "vacancy.familyDetailsHint": "आधिकारिक कागजातमा भएअनुसार परिवारका नाम लेख्नुहोस्। पहिलो र अन्तिम नाम अनिवार्य छन्।",
    "vacancy.middleOptional": "बीचको नाम वैकल्पिक हो।",
    "vacancy.spouseTitle": "पति/पत्नीको नाम",
    "vacancy.spouseHintTitle": "वैवाहिक अवस्था अनुसारको विवरण",
    "vacancy.spouseHint": "विवाहित छनोट गर्दा पति/पत्नीको नामका फिल्डहरू स्वतः देखिनेछन्।",
    "vacancy.selectOption": "छान्नुहोस्...",
    "vacancy.single": "अविवाहित",
    "vacancy.married": "विवाहित",
    "vacancy.divorced": "सम्बन्धविच्छेद",
    "vacancy.male": "पुरुष",
    "vacancy.female": "महिला",
    "vacancy.other": "अन्य",
    "vacancy.priorityProvince": "म प्राथमिकता प्रदेश (१, ३, ४, ५) बाट हुँ",
    "vacancy.fieldComplete": "ठिक छ",
    "vacancy.footerDescription": "सीवाईसी नेपाल लघुवित्त वित्तीय संस्था लिमिटेड — समावेशी वित्तीय पहुँच र नेपालभर रोजगारी निर्माणप्रति प्रतिबद्ध।",
    "vacancy.footerRights": "सर्वाधिकार सुरक्षित।",
    "vacancy.contactIntro": "आफ्नो स्थायी र अस्थायी ठेगाना अंग्रेजी र नेपालीमा, साथै सम्पर्क जानकारी भर्नुहोस्।",
    "vacancy.referencesTitle": "सिफारिसकर्ता",
    "vacancy.referencesHint": "वैकल्पिक। तपाईंको आवेदनको पुष्टि गर्न सक्ने व्यक्ति थप्नुहोस्।",
    "vacancy.reference": "सिफारिसकर्ता",
    "vacancy.referenceName": "नाम",
    "vacancy.referencePhone": "फोन",
    "vacancy.position": "पद",
    "vacancy.educationIntro": "आफ्नो शैक्षिक योग्यता थप्नुहोस्। प्रत्येक विवरण सम्पादन वा हटाउन सकिन्छ।",
    "vacancy.experienceIntro": "आफ्नो कार्य अनुभव थप्नुहोस्। प्रत्येक विवरण सम्पादन वा हटाउन सकिन्छ।",
    "vacancy.documentsIntro": "आवश्यक कागजातहरू अपलोड गर्नुहोस्। प्रत्येक कागजातको स्वीकृत ढाँचा र आकार सीमा तल देखाइएको छ।",
    "vacancy.documents": "कागजातहरू",
    "vacancy.facultyNepali": "संकाय (प्रीति युनिकोड)",
    "vacancy.englishLabel": "अंग्रेजी",
    "vacancy.nepaliLabel": "नेपाली",
    "vacancy.noEducationYet": "अहिलेसम्म कुनै शिक्षा थपिएको छैन।",
    "vacancy.noExperienceYet": "अहिलेसम्म कुनै अनुभव थपिएको छैन।",
    "vacancy.addAnother": "अर्को थप्नुहोस्",
    "vacancy.edit": "सम्पादन",
    "vacancy.save": "सुरक्षित गर्नुहोस्",
    "vacancy.done": "सम्पन्न",
    "vacancy.cancel": "रद्द गर्नुहोस्",
    "vacancy.actions": "कार्यहरू",
    "vacancy.optionalDoc": "वैकल्पिक",
    "vacancy.overviewIntro": "पेश गर्नुअघि सबै विवरण जाँच गर्नुहोस्। सम्पादन गर्न माथिको चरण ट्याबहरू प्रयोग गर्नुहोस्।",
    "vacancy.profile": "प्रोफाइल",
    "vacancy.changePassword": "पासवर्ड परिवर्तन गर्नुहोस्",
    "vacancy.logoff": "लगआउट गर्नुहोस्",
    // Contact fields
    "vacancy.contactDetail": "सम्पर्क विवरण",
    "vacancy.permanentAddress": "स्थायी ठेगाना",
    "vacancy.temporaryAddress": "अस्थायी ठेगाना",
    "vacancy.state": "प्रदेश",
    "vacancy.district": "जिल्ला",
    "vacancy.localLevelType": "स्थानीय तहको प्रकार",
    "vacancy.municipality": "नगरपालिका/गाउँपालिका",
    "vacancy.ward": "वार्ड नम्बर",
    "vacancy.tole": "टोल",
    "vacancy.street": "सडकको नाम",
    "vacancy.streetName": "सडकको नाम",
    "vacancy.wardNo": "वार्ड नम्बर",
    "vacancy.houseNo": "घर नम्बर",
    "vacancy.phone": "फोन",
    "vacancy.email": "इमेल",
    "vacancy.sameAsPermanent": "स्थायी ठेगाना जस्तै",
    "vacancy.permanentAddressNepali": "स्थायी ठेगाना (नेपालीमा)",
    "vacancy.temporaryAddressNepali": "अस्थायी ठेगाना (नेपालीमा)",
    "vacancy.contactInformation": "सम्पर्क जानकारी",
    "vacancy.mobile": "मोबाइल",
    "vacancy.maritalStatus": "वैवाहिक स्थिति",
    "vacancy.citizenshipNumber": "नागरिकता नम्बर",
    "vacancy.citizenshipDistrict": "नागरिकता जारी जिल्ला",
    "vacancy.citizenshipDate": "नागरिकता जारी मिति",
    "vacancy.fatherName": "पिताको नाम",
    "vacancy.motherName": "माताको नाम",
    "vacancy.spouseName": "पतिको/पत्निको नाम",
    "vacancy.grandfatherName": "आमाको/बाजेको नाम",
    "vacancy.religion": "धर्म",
    "vacancy.disability": "अपाङ्गता",
    "vacancy.documentDetail": "कागजात विवरण",
    "vacancy.documentType": "कागजात प्रकार",
    "vacancy.documentTitle": "कागजात नाम",
    "vacancy.download": "डाउनलोड",
    "vacancy.preview": "पूर्वावलोकन",
    // Education fields
    "vacancy.education": "शिक्षा",
    "vacancy.addEducation": "+ शिक्षा विवरण थप्नुहोस्",
    "vacancy.university": "विश्वविद्यालय/बोर्डको नाम",
    "vacancy.institution": "संस्था",
    "vacancy.degree": "डिग्री",
    "vacancy.faculty": "संकाय",
    "vacancy.marks": "अङ्क",
    "vacancy.educationNepali": "शिक्षा (नेपालीमा)",
    "vacancy.universityNepali": "विश्वविद्यालय/बोर्डको नाम (प्रीति युनिकोड)",
    "vacancy.institutionNepali": "संस्था (प्रीति युनिकोड)",
    "vacancy.degreeNepali": "डिग्री (प्रीति युनिकोड)",
    "vacancy.delete": "हटाउनुहोस्",
    // Experience fields
    "vacancy.experience": "अनुभव",
    "vacancy.addExperience": "+ अनुभव थप्नुहोस्",
    "vacancy.organization": "संस्थाको नाम",
    "vacancy.department": "विभाग",
    "vacancy.serviceFrom": "सेवा सुरु मिति",
    "vacancy.serviceTo": "सेवा समाप्त मिति",
    "vacancy.organizationNepali": "संस्थाको नाम (प्रीति युनिकोड)",
    "vacancy.departmentNepali": "विभाग (प्रीति युनिकोड)",
    "vacancy.positionNepali": "पद (प्रीति युनिकोड)",
    // Documents & additional notes
    "vacancy.requiredDocumentsTitle": "आवश्यक कागजात",
    "vacancy.doc.handwrittenApplication": "हातले लेखिएको आवेदन",
    "vacancy.doc.cv": "बायोडाटा / सीभी",
    "vacancy.doc.citizenship": "नागरिकता प्रतिलिपि",
    "vacancy.doc.educationalCertificates": "शैक्षिक प्रमाणपत्रहरू",
    "vacancy.doc.experienceCertificates": "अनुभव प्रमाणपत्रहरू",
    "vacancy.doc.photograph": "पासपोर्ट-साइज फोटो",
    "vacancy.doc.trainingCertificates": "प्रशिक्षण प्रमाणपत्रहरू (यदि छन्)",
    "vacancy.allDocumentsPdf": "प्रत्येक कागजात तल देखाइएको ढाँचा र आकारमा अपलोड गर्नुहोस्।",
    "vacancy.workLocation": "छानिएका उम्मेदवारहरू संगठनको आवश्यकताअनुसार कुनै पनि शाखा, प्रदेश, क्लस्टर, वा विभागमा नियुक्त हुन सक्नेछन्।",
    "vacancy.additionalPreferencesTitle": "थप प्राथमिकताहरू",
    "vacancy.pref.motorcycleLicense": "मोटरसाइकल चालक अनुमतिपत्र भएका",
    "vacancy.pref.computerKnowledge": "कम्प्युटर ज्ञान भएका",
    "vacancy.pref.microfinanceExperience": "सूक्ष्मवित्त संस्थामा अनुभव भएका",
    "vacancy.mandatoryEconomicsQuestion": "के तपाईंले अनिवार्य विषयको रूपमा अर्थशास्त्र अध्ययन गर्नुभएको थियो?",
    "vacancy.mandatoryEconomicsNote": "व्यवस्थापन तथा शिक्षा (आर्ट्स र एजुकेशन) क्षेेत्रका उम्मेदवारहरूले अर्थशास्त्र अनिवार्य विषयको रूपमा पढेको हुनुपर्छ।",
    // --- Candidate shell / navigation ---
    "vacancy.candidateSection": "उम्मेदवार खण्ड",
    "vacancy.onlineApplicationSystem": "अनलाइन आवेदन प्रणाली",
    "vacancy.home": "गृहपृष्ठ",
    "vacancy.previous": "पछाडि",
    "vacancy.next": "अर्को",
    "vacancy.applyHeading": "जागिरका लागि आवेदन दिन तलको जानकारी भर्नुहोस्",
    "vacancy.applicationType": "आवेदन प्रकार",
    "vacancy.confirmApply": "मैले सबै निर्देशनहरू ध्यानपूर्वक पढेको छु, सबै आवश्यक कागजात पूरा गरेको छु र जागिरका लागि आवेदन दिएको छु।",
    "vacancy.payNow": "तपाईंको जानकारी सुरक्षित गरी अहिले भुक्तानी गर्नुहोस्",
    // --- Save / storage ---
    "vacancy.saveDraft": "फाराम सुरक्षित गर्नुहोस्",
    "vacancy.draftSaved": "सुरक्षित भयो",
    "vacancy.saving": "सुरक्षित गर्दै…",
    "vacancy.saveDraftHint": "तपाईं अधुरो फाराम सुरक्षित गरी पछि फर्कन सक्नुहुन्छ।",
    "vacancy.attachmentStorage": "संलग्न कागजात आकार",
    "vacancy.maxLabel": "अधिकतम",
    // --- Family (Nepali) + hints ---
    "vacancy.familyDetailsNepali": "परिवार विवरण (नेपालीमा)",
    "vacancy.fatherNameNepali": "पिताको नाम (नेपालीमा)",
    "vacancy.motherNameNepali": "माताको नाम (नेपालीमा)",
    "vacancy.grandfatherNameNepali": "बाजेको नाम (नेपालीमा)",
    "vacancy.spouseTitleNepali": "पति/पत्नीको नाम (नेपालीमा)",
    "vacancy.devanagariHint": "नेपाली (देवनागरी) मा लेख्नुहोस्, जस्तै: राम बहादुर",
    "vacancy.englishHint": "अंग्रेजी (A–Z) मा लेख्नुहोस्",
    // --- Documents (labels + notes) ---
    "vacancy.doc.citizenshipFront": "नागरिकता (अगाडि)",
    "vacancy.doc.citizenshipBack": "नागरिकता (पछाडि)",
    "vacancy.doc.experienceLetter": "अनुभव पत्र",
    "vacancy.doc.referenceLetter": "सिफारिस पत्र",
    "vacancy.requiredDocsIntro": "स्पष्ट स्क्यान अपलोड गर्नुहोस्। प्रत्येक कागजातको स्वीकृत ढाँचा र आकार सीमा तल देखाइएको छ।",
    "vacancy.replaceFile": "बदल्नुहोस्",
    "vacancy.chooseFile": "फाइल छान्नुहोस्",
    "vacancy.docRequired": "यो कागजात अनिवार्य छ।",
    // --- Education detail form ---
    "vacancy.educationDetailTitle": "शैक्षिक योग्यताको विवरण",
    "vacancy.boardUniversity": "बोर्ड / विश्वविद्यालयको नाम",
    "vacancy.otherBoardUniversity": "अन्य विश्वविद्यालय / बोर्ड नाम",
    "vacancy.academicDegree": "शैक्षिक उपाधि",
    "vacancy.facultyGroup": "संकाय / समूह",
    "vacancy.otherFaculty": "अन्य शैक्षिक संकाय",
    "vacancy.mainSubject": "मूल विषय",
    "vacancy.gradeType": "ग्रेड / श्रेणी",
    "vacancy.gradeName": "ग्रेड / श्रेणी नाम",
    "vacancy.gpa": "जीपीए / प्रतिशत",
    "vacancy.eduCertificate": "शैक्षिक प्रमाणपत्र",
    "vacancy.characterCertificate": "चारित्रिक प्रमाणपत्र",
    "vacancy.equivalenceCertificate": "समकक्षता प्रमाणपत्र",
    "vacancy.eduUploadNote": "केवल .jpg, .jpeg, .png वा .pdf अपलोड गर्नुहोस्",
    "vacancy.othersOption": "अन्य",
    "vacancy.gradeOption": "ग्रेड",
    "vacancy.divisionOption": "श्रेणी",
    "vacancy.percentageOption": "प्रतिशत",
  },
};

export function VacancyLanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<VacancyLanguage>("ne");

  const t = (key: string): string => {
    return vacancyTranslations[language][key as keyof typeof vacancyTranslations["en"]] || key;
  };

  return (
    <VacancyLanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </VacancyLanguageContext.Provider>
  );
}

export function useVacancyLanguage() {
  const context = useContext(VacancyLanguageContext);
  if (!context) {
    throw new Error("useVacancyLanguage must be used within VacancyLanguageProvider");
  }
  return context;
}
